apiVersion: v1
kind: Secret
metadata:
  name: backend-db-credentials
  namespace: smart-asset-manager
type: Opaque
stringData:
  PGHOST: postgres.database.svc.cluster.local
  PGUSER: mosalam_admin
  PGPASSWORD: ChangeMe123!
  PGDATABASE: mosalam_db
  REDIS_URL: redis://redis.cache.svc.cluster.local:6379
---
apiVersion: v1
kind: Secret
metadata:
  name: shared-api-key
  namespace: smart-asset-manager
type: Opaque
stringData:
  API_KEY: CHANGE_ME_TEMP_KEY_123
